services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bbs2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bbs2"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/bbs2
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COLLECTION_NAME: bbs_rag_collection
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    # volumes:
    #   - ./backend:/app
    #   - /app/.venv  # Exclude venv from volume mount
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  postgres_data: